/**
 * Blockchain Proof
 * With the Blockchain Proof API it is easy to prove or disprove existence of data at a certain point in time. Behind the scenes it stores entries using the Factom (bitcoin), Multichain or Ethereum blockchain by means of our generic blockchain API.    The flow is generally as follows:  1. Make sure a configuration is present  2. Register content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing  3. Verify content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing. You will get back whether the content has been registered previously or not    Full API Documentation: https://docs.sphereon.com/api/blockchain-proof/0.9/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKBlockchainProof/ApiClient', 'SphereonSDKBlockchainProof/model/CommittedEntry'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CommittedEntry'));
  } else {
    // Browser globals (root is window)
    if (!root.BlockchainProof) {
      root.BlockchainProof = {};
    }
    root.BlockchainProof.VerifyContentResponse = factory(root.BlockchainProof.ApiClient, root.BlockchainProof.CommittedEntry);
  }
}(this, function(ApiClient, CommittedEntry) {
  'use strict';




  /**
   * The VerifyContentResponse model module.
   * @module SphereonSDKBlockchainProof/model/VerifyContentResponse
   * @version 0.9
   */

  /**
   * Constructs a new <code>VerifyContentResponse</code>.
   * Verify Content response
   * @alias module:SphereonSDKBlockchainProof/model/VerifyContentResponse
   * @class
   * @param contextName {String} 
   */
  var exports = function(contextName) {
    var _this = this;


    _this['contextName'] = contextName;





  };

  /**
   * Constructs a <code>VerifyContentResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKBlockchainProof/model/VerifyContentResponse} obj Optional instance to populate.
   * @return {module:SphereonSDKBlockchainProof/model/VerifyContentResponse} The populated <code>VerifyContentResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('registrationTime')) {
        obj['registrationTime'] = ApiClient.convertToType(data['registrationTime'], 'Date');
      }
      if (data.hasOwnProperty('contextName')) {
        obj['contextName'] = ApiClient.convertToType(data['contextName'], 'String');
      }
      if (data.hasOwnProperty('singleProofChain')) {
        obj['singleProofChain'] = CommittedEntry.constructFromObject(data['singleProofChain']);
      }
      if (data.hasOwnProperty('contentRegistrationChainTypes')) {
        obj['contentRegistrationChainTypes'] = ApiClient.convertToType(data['contentRegistrationChainTypes'], ['String']);
      }
      if (data.hasOwnProperty('requestId')) {
        obj['requestId'] = ApiClient.convertToType(data['requestId'], 'String');
      }
      if (data.hasOwnProperty('perHashProofChain')) {
        obj['perHashProofChain'] = CommittedEntry.constructFromObject(data['perHashProofChain']);
      }
      if (data.hasOwnProperty('registrationState')) {
        obj['registrationState'] = ApiClient.convertToType(data['registrationState'], 'String');
      }
    }
    return obj;
  }

  /**
   * This is the first registration time from the singleProofChain or the perHashProofChain
   * @member {Date} registrationTime
   */
  exports.prototype['registrationTime'] = undefined;
  /**
   * @member {String} contextName
   */
  exports.prototype['contextName'] = undefined;
  /**
   * This is the single proof chain where all hashes are stored (if configured)
   * @member {module:SphereonSDKBlockchainProof/model/CommittedEntry} singleProofChain
   */
  exports.prototype['singleProofChain'] = undefined;
  /**
   * A set of content registration targets
   * @member {Array.<module:SphereonSDKBlockchainProof/model/VerifyContentResponse.ContentRegistrationChainTypesEnum>} contentRegistrationChainTypes
   */
  exports.prototype['contentRegistrationChainTypes'] = undefined;
  /**
   * @member {String} requestId
   */
  exports.prototype['requestId'] = undefined;
  /**
   * This is the proof chain specific for the current hash (if configured)
   * @member {module:SphereonSDKBlockchainProof/model/CommittedEntry} perHashProofChain
   */
  exports.prototype['perHashProofChain'] = undefined;
  /**
   * This is the registration state from the singleProofChain or the perHashProofChain. If one of the chains has a registration this will return REGISTERED
   * @member {module:SphereonSDKBlockchainProof/model/VerifyContentResponse.RegistrationStateEnum} registrationState
   */
  exports.prototype['registrationState'] = undefined;


  /**
   * Allowed values for the <code>contentRegistrationChainTypes</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ContentRegistrationChainTypesEnum = {
    /**
     * value: "PER_HASH_PROOF_CHAIN"
     * @const
     */
    "PER_HASH_PROOF_CHAIN": "PER_HASH_PROOF_CHAIN",
    /**
     * value: "SINGLE_PROOF_CHAIN"
     * @const
     */
    "SINGLE_PROOF_CHAIN": "SINGLE_PROOF_CHAIN"  };

  /**
   * Allowed values for the <code>registrationState</code> property.
   * @enum {String}
   * @readonly
   */
  exports.RegistrationStateEnum = {
    /**
     * value: "NOT_REGISTERED"
     * @const
     */
    "NOT_REGISTERED": "NOT_REGISTERED",
    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",
    /**
     * value: "REGISTERED"
     * @const
     */
    "REGISTERED": "REGISTERED"  };


  return exports;
}));


