/*
 * Blockchain Proof
 * With the Blockchain Proof API it is easy to prove or disprove existence of data at a certain point in time. Behind the scenes it stores entries using the Factom (bitcoin), Multichain or Ethereum blockchain by means of our generic blockchain API.    The flow is generally as follows:  1. Make sure a configuration is present  2. Register content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing  3. Verify content by uploading a file, some content, or providing a Stream Location from the Storage API. When you upload content you have to tell the API whether the data has already been hashed or not. If not, or when uploading a file or stream location, the API will take care of the hashing. You will get back whether the content has been registered previously or not    Full API Documentation: https://docs.sphereon.com/api/blockchain-proof/0.9/html  Interactive testing: A web based test console is available in the Sphereon API Store at https://store.sphereon.com
 *
 * OpenAPI spec version: 0.9
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.sphereon.sdk.blockchain.proof.api;

import com.sphereon.sdk.blockchain.proof.handler.ApiException;
import com.sphereon.sdk.blockchain.proof.model.ContentRequest;
import com.sphereon.sdk.blockchain.proof.model.StreamLocation;
import org.junit.Ignore;
import org.junit.Test;

import java.io.File;

/**
 * API tests for VerificationApi
 */
@Ignore
public class VerificationApiTest {

    private final VerificationApi api = new VerificationApi();


    /**
     * Verify content
     * <p>
     * Verify content. Please provide the content in the request. You also have to provide whether you have hashed the content yourself, or whether is should be done on the server side
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyUsingContentTest() throws ApiException {
        String configName = null;
        ContentRequest existence = null;
        String secret = null;

        // TODO: test validations
    }


    /**
     * Verify hash using the Storage API
     * <p>
     * Verify a hash of file/blob by supplying a Stream location of the Storage API. This Stream Location maps to a location of a file/blob on some remote cloud storage. Hashing will be done on the server side Please note that the binary data itself will not be stored, only the hash. Use the registerUsingContent endpoint if you&#39;d like to store content
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyUsingLocationTest() throws ApiException {
        String configName = null;
        StreamLocation streamLocation = null;
        String requestId = null;
        String secret = null;

        // TODO: test validations
    }


    /**
     * Verify bytestream/file hash
     * <p>
     * Verify a hash of content by supplying a file or some other binary data. Hashing will be done on the server side. Please note that the binary data itself will not be stored, only the hash. Use the registerUsingContent endpoint if you&#39;d like to store content
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void verifyUsingStreamTest() throws ApiException {
        String configName = null;
        File stream = null;
        String fileName = null;
        String secret = null;

        // TODO: test validations
    }

}
